# system parameters
seed: 0
multiprocessing: True
num_process: 64

# data parameters
log_dir: <path_to_log_directory>
task_metadata_path: <path_to_processed_data_directory>/<dataset_name>/meta_data.json
target_data_dir: <path_to_processed_data_directory>/<dataset_name>/HF/test

# model parameters
llm_path: <path_to_api_key>
llm_model: chatgpt
llm_version: gpt-4o

# sampling parameters
num_samples: 30
num_examples: 1

# True for visual prompt, False for text-only prompt
use_vis: True
# True for enabling visualization generator, False for a fixed visualization
plan_vis: True

# If use_vis is False, the following parameters are used for text-only prompt
txt_style: raw waveform # refer to core/txt_generator.py for available styles
txt_rounding_points: 2 # round the data to 2 decimal points
txt_sampling_rate: 100 # resample data in the prompt

# If use_vis is True and plan_vis is False, the following parameters are used for visual prompt
vis_func: raw waveform # refer to core/visualizer.py for available functions
vis_args: {} # visualization parameters
vis_knowledge: null